version: '3.8'

services:
  db:
    image: postgres:13.2
    ports:
      - ${DB_POINTER_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DATABASE}
    container_name: devschools_db

  devschools:
    build: .
    container_name: devschools_backend
    volumes:
      - ./:/devschools
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
